CREATE DATABASE IF NOT EXISTS ask_bagbin CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ask_bagbin;

CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('super_admin','admin','editor') NOT NULL DEFAULT 'admin',
  active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings (
  id INT PRIMARY KEY,
  website_open TINYINT(1) NOT NULL DEFAULT 1,
  maintenance_message VARCHAR(500) DEFAULT 'Our website is temporarily unavailable. Please check back soon.',
  logo_url VARCHAR(500) DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO settings (id, website_open) VALUES (1,1)
ON DUPLICATE KEY UPDATE id=id;

CREATE TABLE IF NOT EXISTS beneficiaries (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(180) NOT NULL,
  programme VARCHAR(180) DEFAULT NULL,
  institution VARCHAR(220) DEFAULT NULL,
  level VARCHAR(100) DEFAULT NULL,
  location VARCHAR(180) DEFAULT NULL,
  status ENUM('Active','Completed','Inactive') DEFAULT 'Active',
  image_url VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(220) NOT NULL,
  description TEXT,
  category VARCHAR(120) DEFAULT NULL,
  location VARCHAR(180) DEFAULT NULL,
  status ENUM('Draft','Published','Archived') DEFAULT 'Draft',
  image_url VARCHAR(500) DEFAULT NULL,
  impact_summary TEXT,
  beneficiaries_count INT DEFAULT NULL,
  start_date DATE DEFAULT NULL,
  completion_date DATE DEFAULT NULL,
  before_image_url VARCHAR(500) DEFAULT NULL,
  after_image_url VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS news (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(220) NOT NULL,
  excerpt TEXT,
  content LONGTEXT,
  author VARCHAR(120) DEFAULT NULL,
  status ENUM('Draft','Published','Archived') DEFAULT 'Draft',
  image_url VARCHAR(500) DEFAULT NULL,
  published_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scholarship_applications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(180) NOT NULL,
  email VARCHAR(190) NOT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  programme VARCHAR(180) DEFAULT NULL,
  institution VARCHAR(220) DEFAULT NULL,
  level VARCHAR(100) DEFAULT NULL,
  date_of_birth DATE DEFAULT NULL,
  student_id VARCHAR(120) DEFAULT NULL,
  statement TEXT,
  document_url VARCHAR(500) DEFAULT NULL,
  status ENUM('Pending','Approved','Rejected') DEFAULT 'Pending',
  submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS partnerships (
  id INT AUTO_INCREMENT PRIMARY KEY,
  organization_name VARCHAR(220) NOT NULL,
  contact_name VARCHAR(180) DEFAULT NULL,
  email VARCHAR(190) DEFAULT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  message TEXT,
  status ENUM('New','Contacted','Approved','Rejected') DEFAULT 'New',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS volunteers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(180) NOT NULL,
  email VARCHAR(190) NOT NULL,
  phone VARCHAR(50) DEFAULT NULL,
  skills VARCHAR(500) DEFAULT NULL,
  message TEXT,
  status ENUM('New','Contacted','Approved','Rejected') DEFAULT 'New',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(180) NOT NULL,
  email VARCHAR(190) NOT NULL,
  subject VARCHAR(220) DEFAULT NULL,
  message TEXT NOT NULL,
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  admin_id INT NULL,
  action VARCHAR(80) NOT NULL,
  resource VARCHAR(80) NOT NULL,
  record_id INT NULL,
  details JSON NULL,
  ip_address VARCHAR(64) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_audit_created (created_at),
  INDEX idx_audit_resource (resource)
);
